name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run deploy commands on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: eagombar.uk
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/eagombar.uk
            git pull
            sudo nginx -s reload
